#!/bin/bash

DT=`date +%c`
SCRIPTS_PATH=${UTIL_DIR}
LOG_PATH=${ydb_dir}/log
LOG_FILE=${LOG_PATH}/start_replication.log_`date +"%y%m%d-%H%M%S"`

filter=$1

. ${SCRIPTS_PATH}/replication_check
. ${SCRIPTS_PATH}/replication_start


if [ ${multi_site} == "N" ]
then
	echo "$DT Start replication in PRIMARY mode"

	start_replication_in_primary_mode 2>&1 | tee ${LOG_FILE} 	

	check_source_server	

	stat_check

elif [ ${multi_site} == "Y" ]
then

	export MODE="PRIMARY"

	echo "$DT Start Multi-Site replication in PRIMARY mode"

        ${SCRIPTS_PATH}/start_multi_site_replication 2>&1 | tee ${LOG_FILE}

        check_source_server

        stat_check
else
	echo "$DT multi_site paramter not defined or defined wrongly !!!"
	echo "$DT Please Check ydbenv before process"
fi
