#!/bin/sh
#
# Usage: uxprint printer_name filename copies notify
# Convert UNIX files to dos format files (if required) and print on specified 
# printer.
#
# Harsha Lakshmikantha  02/18/96
#
#-----Revision History-------------------------------------------------------
#
# Harsha Lakshmikantha  12/07/01
#	 Added sections for Linux, Solaris (SunOS), and OS/390.
#
# Rick Silvagni  10/27/97
#	 Modified not to use ux2dos utility for HP-UX. This was causing
#        control characters to be cut out before reaching the print queue.
#
#-----------------------------------------------------------------------------
#
#               Parameters
#
# $1    -       Printer name
# $2    -       File Name
# $3    -       Number of copies
# $4    -       Notify user
#
#

os=`uname`
case $os in
	"OSF1")
		#	
		# P - Print job destination.	
		#	
		# # - Produces the specified number of copies of the output.
		#	
		# m - Sends mail when spooling is completed.
		#	

                if [ $# -eq 4 ]
			then
				if [ $4 = "NOTIFY" ]
				then
					ux2dos $2 | lpr -P$1 -#$3 -m
					#lpr -P$1 -#$3 -m $2
				fi
			else
				ux2dos $2 | lpr -P$1 -#$3
				#lpr -P$1 -#$3 $2
		fi
       	 	;;

	"AIX")
		#	
		# P - Forces output to the specified printer.
		#	
		# # - Produces the specified number of copies of the output.
		#	
		# m - Sends mail upon completion of spooling. 	
		#	

                if [ $# -eq 4 ]
			then
				if [ $4 = "NOTIFY" ]
				then
					lpr -P$1 -#$3 $2
					#lpr -P$1 -#$3 -m $2
					#qprt -P$1 -N$3 -C $2
				fi
			else
				lpr -P$1 -#$3 $2
				#qprt -P$1 -N$3 $2
		fi
       	 	;;

	"HP-UX")
		#
		# d - Printer that is to do the printing.
		# 
		# n - Print the specified number of copies of the output.
		#
		# w - Write a message to the user's terminal after the
                #     request has been printed.  If the user is not logged in
                #     or if rlpdaemon is not running on the user's local system
                #     mail will be sent instead.
		#

		if [ $# -eq 4 ]
                        then
                                if [ $4 = "NOTIFY" ]
                                then
                                        lp -d$1 -n$3 -w $2
                                        #ux2dos $2 | lp -d$1 -n$3 -w
                                fi
                        else
                                lp -d$1 -n$3 $2
                                #ux2dos $2 | lp -d$1 -n$3
                fi
       	 	;;

	"Linux")
		#	
		# P - Print job destination.	
		#	
		# # - Produces the specified number of copies of the output.
		#	
		# m - Sends mail when spooling is completed. (Not supported on s390)
		#	

		lx=`uname -m`
		if [ $lx = "s390" ]
		then
			lpr -P$1 -#$3 $2
		else
                	if [ $# -eq 4 ]
				then
					if [ $4 = "NOTIFY" ]
					then
						lpr -P$1 -#$3 -m $2
					fi
				else
					lpr -P$1 -#$3 $2
			fi
		fi
       	 	;;

	"SunOS")
		#	
		# P - Forces output to the specified printer.
		#	
		# # - Produces the specified number of copies of the output.
		#	
		# m - Sends mail upon completion of spooling. 	
		#	

                if [ $# -eq 4 ]
			then
				if [ $4 = "NOTIFY" ]
				then
					/usr/ucb/lpr -P$1 -#$3 -m $2
				fi
			else
				/usr/ucb/lpr -P$1 -#$3 $2
		fi
       	 	;;

	"OS/390")
                #
                # P - Print job destination.
                #
                # # - Produces the specified number of copies of the output.
                #
                # m - Sends mail when spooling is completed.
                #

                if [ $# -eq 4 ]
                        then
                                if [ $4 = "NOTIFY" ]
                                then
                                        #ux2dos $2 | lp -d$1 -n$3
                                        #lp -d$1 -n$3 -m $2
                                        # The -m is not implemented on OS/390
                                        lp -d$1 -n$3 $2
                                fi
                        else
                                #ux2dos $2 | lp -d$1 -n$3
                                lp -d$1 -n$3 $2
                fi
                ;;
	*)
       	 	;;
esac
